name: Go
on: [push]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  LAMBDA_NAME: ${{ vars.LAMBDA_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: go get .

      - name: Test with the Go CLI
        run: go test ./...

      - name: Build
        run: CGO_ENABLED=0 go build -o main

      - name: Zip
        run: zip deploy.zip main

      - name: Added templates to zip
        run: zip -r deploy.zip templates/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Upload code to AWS
        run: |
          aws lambda update-function-code --function-name ${{ env.LAMBDA_NAME }} --zip-file fileb://deploy.zip
          echo "Done!"
