name: deploy

on:
  push:
    branches:
      - '*'

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
  
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: Install dependencies
      run: |
        go get github.com/aws/aws-lambda-go@v1.41.0
        go get go.mongodb.org/mongo-driver@v1.13.0
        go get go.uber.org/zap@v1.26.0

    - name: Build
      run: go build ./...

    - name: Test
      run: go test -v ./...